services:
  project-ts:
    container_name: project-ts
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file: .env
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    command: npm run dev
